GET http://localhost:3001/todos

###
POST http://localhost:3001/todo/new
Content-Type: application/json

{
    "text": "Do it on Typescript!"
}

###

DELETE http://localhost:3001/todo/delete/6133faf8e42022f69e9fb36d

###

PUT http://localhost:3001/todo/complete/6133fb79e42022f69e9fb370